const jsonResponse = [
  {
    Apartment_Type: "1BR",
    Apartment_Occupany_Tax_State: 6,
    Street: "water st",
    Apartment_Unit_Id: "1543",
    Apartment_Occupany_Tax_City: 7,
    Apartment__Nearest_Landmarks: {
      Hollywood: "9 Miles",
      Beach: "29 Miles",
      "Central Square": "3 Miles",
      Airport: "1 Miles"
    },
    Apartment_Service_Fee: 8,
    Apartment_Contact: "+1 (803) 788-688",
    Apartment_Price_Per_Week: 875,
    Apartment_Business_Amenities: {
      Cable: "Yes",
      "Full Kitchen": "Yes",
      "Coffe Machine": "Yes",
      Iron: "Yes",
      "Smart TV": "Yes",
      "High Speed Internet": "Yes"
    },
    Apartment_Cleaning_Fee: 40,
    Apartment_Monthly_Discount: 10,
    Apartment_Latitue: "45.524548",
    Apartment_Price_Per_Month: 3750,
    Apartment_BathRoom_Cnt: 1,
    Apartment_Avail_From_Date: "2019-03-01T00:00:00.000Z",
    Apartment_Desc: null,
    Apartment_Status: "Active",
    Apartment_Name: "Trendy 1BR with Retail View",
    Apartment_List_Of_Images: [
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-2.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-3.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-4.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-5.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-6.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-7.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-8.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-9.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-10.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-11.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-12.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-13.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-14.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-15.jpg"
    ],
    City: "plano",
    Apartment_Price_Per_Night: 125,
    Country: "United States",
    Apartment_Full_Address: "6080 Water St Plano Texas 75024 USA",
    Apartment_Weekly_Discount: 5,
    Apartment_Ratings: 3,
    Apartment_Max_Occupants: 2,
    Apartment_Floor: 5,
    Apartment_Min_Price: 110,
    Create_Date: "2019-03-28T09:40:29.613Z",
    State: "texas",
    Apartment_Services: {
      Housekeeping: "Yes",
      Drycleaning: "Yes",
      Breakfast: "Yes",
      "Uber/Lyft": "No"
    },
    Apartment_Longitude: "-122.6749817",
    Apartment_Image:
      "http://www.urbanlightsresidential.com/wp-content/uploads/2019/02/Naseem-02122019-1-2.jpg",
    Apartment_Avail_To_Date: "2019-12-31T00:00:00.000Z",
    Apartment_Long_Term_Deposit: 15,
    Apartment_BedRoom_Cnt: 1,
    Apartment_Max_Price: 150,
    User_Id: "1543",
    Apartment_Terms_Conds: "Minimum one night stay is required",
    Create_By: "admin",
    Apartment_Reviews: "average",
    Apartment_Amenities: {
      "Washer/Dryer": "Yes",
      "Parking Type": "Attached Garage",
      "Pets Allowed": "No",
      "Floor Type": "Hardwood",
      "Air Conditioning": "No",
      Balcony: "No",
      "Swimming Pool": "Yes",
      "Fitness Center": "Yes",
      Mailroom: "Yes",
      Patio: "No"
    },
    Id: "so_inventory",
    Pincode: "75024"
  },
  {
    Apartment_Type: "1BR",
    Apartment_Occupany_Tax_State: 6,
    Street: "water st",
    Apartment_Unit_Id: "1523",
    Apartment_Occupany_Tax_City: 7,
    Apartment__Nearest_Landmarks: {
      Hollywood: "9 Miles",
      Beach: "29 Miles",
      "Central Square": "3 Miles",
      Airport: "1 Miles"
    },
    Apartment_Service_Fee: 8,
    Apartment_Contact: "+1 (803) 788-688",
    Apartment_Price_Per_Week: 875,
    Apartment_Business_Amenities: {
      Cable: "Yes",
      "Full Kitchen": "Yes",
      "Coffe Machine": "Yes",
      Iron: "Yes",
      "Smart TV": "Yes",
      "High Speed Internet": "Yes"
    },
    Apartment_Cleaning_Fee: 40,
    Apartment_Monthly_Discount: 10,
    Apartment_Latitue: "45.524698",
    Apartment_Price_Per_Month: 3750,
    Apartment_BathRoom_Cnt: 1,
    Apartment_Avail_From_Date: "2019-03-01T00:00:00.000Z",
    Apartment_Desc: null,
    Apartment_Status: "Active",
    Apartment_Name: "Trendy 1BR with Retail View",
    Apartment_List_Of_Images: [
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-2.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-3.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-4.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-5.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-6.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-7.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-8.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-9.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-10.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-11.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-12.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-13.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-14.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-15.jpg"
    ],
    City: "plano",
    Apartment_Price_Per_Night: 125,
    Country: "United States",
    Apartment_Full_Address: "6080 Water St Plano Texas 75024 USA",
    Apartment_Weekly_Discount: 5,
    Apartment_Ratings: 3,
    Apartment_Min_Price: 110,
    Create_Date: "2019-03-28T09:40:31.089Z",
    Apartment_Max_Occupants: 2,
    Apartment_Floor: 5,
    State: "texas",
    Apartment_Services: {
      Housekeeping: "Yes",
      Drycleaning: "Yes",
      Breakfast: "Yes",
      "Uber/Lyft": "No"
    },
    Apartment_Longitude: "-122.6655507",
    Apartment_Image:
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-1.jpg",
    Apartment_Avail_To_Date: "2019-12-31T00:00:00.000Z",
    Apartment_Long_Term_Deposit: 15,
    Apartment_Max_Price: 150,
    Apartment_BedRoom_Cnt: 1,
    User_Id: "1523",
    Apartment_Terms_Conds: "Minimum one night stay is required",
    Create_By: "admin",
    Apartment_Reviews: "average",
    Apartment_Amenities: {
      "Washer/Dryer": "Yes",
      "Parking Type": "Attached Garage",
      "Pets Allowed": "No",
      "Floor Type": "Hardwood",
      "Air Conditioning": "No",
      Balcony: "No",
      "Swimming Pool": "Yes",
      "Fitness Center": "Yes",
      Mailroom: "Yes",
      Patio: "No"
    },
    Id: "so_inventory",
    Pincode: "75024"
  },
  {
    Apartment_Type: "1BR",
    Apartment_Occupany_Tax_State: 6,
    Street: "water st",
    Apartment_Unit_Id: "1410",
    Apartment_Occupany_Tax_City: 7,
    Apartment__Nearest_Landmarks: {
      Hollywood: "9 Miles",
      Beach: "29 Miles",
      "Central Square": "3 Miles",
      Airport: "1 Miles"
    },
    Apartment_Service_Fee: 8,
    Apartment_Contact: "+1 (803) 788-688",
    Apartment_Price_Per_Week: 875,
    Apartment_Business_Amenities: {
      Cable: "Yes",
      "Full Kitchen": "Yes",
      "Coffe Machine": "Yes",
      Iron: "Yes",
      "Smart TV": "Yes",
      "High Speed Internet": "Yes"
    },
    Apartment_Cleaning_Fee: 40,
    Apartment_Monthly_Discount: 10,
    Apartment_Latitue: "45.5230786,",
    Apartment_Price_Per_Month: 3750,
    Apartment_BathRoom_Cnt: 1,
    Apartment_Avail_From_Date: "2019-03-01T00:00:00.000Z",
    Apartment_Desc: null,
    Apartment_Status: "Active",
    Apartment_Name: "Trendy 1BR with Retail View",
    Apartment_List_Of_Images: [
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-2.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-3.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-4.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-5.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-6.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-7.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-8.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-9.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-10.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-11.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-12.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-13.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-14.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-15.jpg"
    ],
    City: "plano",
    Apartment_Price_Per_Night: 125,
    Country: "United States",
    Apartment_Full_Address: "6080 Water St Plano Texas 75024 USA",
    Apartment_Weekly_Discount: 5,
    Apartment_Ratings: 3,
    Apartment_Max_Occupants: 2,
    Apartment_Floor: 4,
    Apartment_Min_Price: 110,
    Create_Date: "2019-03-28T09:40:31.089Z",
    State: "texas",
    Apartment_Services: {
      Housekeeping: "Yes",
      Drycleaning: "Yes",
      Breakfast: "Yes",
      "Uber/Lyft": "No"
    },
    Apartment_Longitude: "-122.6701034",
    Apartment_Image:
      "http://www.urbanlightsresidential.com/wp-content/uploads/2019/02/Naseem-02122019-6.jpg",
    Apartment_Avail_To_Date: "2019-12-31T00:00:00.000Z",
    Apartment_Long_Term_Deposit: 15,
    Apartment_BedRoom_Cnt: 1,
    Apartment_Max_Price: 150,
    User_Id: "1410",
    Apartment_Terms_Conds: "Minimum one night stay is required",
    Create_By: "admin",
    Apartment_Reviews: "average",
    Apartment_Amenities: {
      "Washer/Dryer": "Yes",
      "Parking Type": "Attached Garage",
      "Pets Allowed": "No",
      "Floor Type": "Hardwood",
      "Air Conditioning": "No",
      Balcony: "No",
      "Swimming Pool": "Yes",
      "Fitness Center": "Yes",
      Mailroom: "Yes",
      Patio: "No"
    },
    Id: "so_inventory",
    Pincode: "75024"
  },
  {
    Apartment_Type: "1BR",
    Apartment_Occupany_Tax_State: 6,
    Street: "water st",
    Apartment_Unit_Id: "1326",
    Apartment_Occupany_Tax_City: 7,
    Apartment__Nearest_Landmarks: {
      Hollywood: "9 Miles",
      Beach: "29 Miles",
      "Central Square": "3 Miles",
      Airport: "1 Miles"
    },
    Apartment_Service_Fee: 8,
    Apartment_Contact: "+1 (803) 788-688",
    Apartment_Price_Per_Week: 875,
    Apartment_Business_Amenities: {
      Cable: "Yes",
      "Full Kitchen": "Yes",
      "Coffe Machine": "Yes",
      Iron: "Yes",
      "Smart TV": "Yes",
      "High Speed Internet": "Yes"
    },
    Apartment_Cleaning_Fee: 40,
    Apartment_Monthly_Discount: 10,
    Apartment_Latitue: " 45.521016",
    Apartment_Price_Per_Month: 3750,
    Apartment_BathRoom_Cnt: 1,
    Apartment_Avail_From_Date: "2019-03-01T00:00:00.000Z",
    Apartment_Desc: null,
    Apartment_Status: "Active",
    Apartment_Name: "Sunny 1BR with Courtyard View",
    Apartment_List_Of_Images: [
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-2.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-3.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-4.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-5.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-6.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-7.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-8.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-9.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-10.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-11.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-12.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-13.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-14.jpg",
      "http://www.urbanlightsresidential.com/wp-content/uploads/2018/11/Naseem-Waters-11032018-15.jpg"
    ],
    City: "plano",
    Apartment_Price_Per_Night: 125,
    Country: "United States",
    Apartment_Full_Address: "6080 Water St Plano Texas 75024 USA",
    Apartment_Weekly_Discount: 5,
    Apartment_Ratings: 3,
    Apartment_Max_Occupants: 2,
    Apartment_Floor: 3,
    Apartment_Min_Price: 110,
    Create_Date: "2019-03-28T09:40:30.936Z",
    State: "texas",
    Apartment_Services: {
      Housekeeping: "Yes",
      Drycleaning: "Yes",
      Breakfast: "Yes",
      "Uber/Lyft": "No"
    },
    Apartment_Longitude: "-122.6561917",
    Apartment_Image:
      "http://www.urbanlightsresidential.com/wp-content/uploads/2019/03/Naseem-09012018-3.jpg",
    Apartment_Avail_To_Date: "2019-12-31T00:00:00.000Z",
    Apartment_Long_Term_Deposit: 15,
    Apartment_BedRoom_Cnt: 1,
    Apartment_Max_Price: 150,
    User_Id: "1326",
    Apartment_Terms_Conds: "Minimum one night stay is required",
    Create_By: "admin",
    Apartment_Reviews: "average",
    Apartment_Amenities: {
      "Washer/Dryer": "Yes",
      "Parking Type": "Attached Garage",
      "Pets Allowed": "No",
      "Floor Type": "Hardwood",
      "Air Conditioning": "No",
      Balcony: "No",
      "Swimming Pool": "Yes",
      "Fitness Center": "Yes",
      Mailroom: "Yes",
      Patio: "No"
    },
    Id: "so_inventory",
    Pincode: "75024"
  }
];
export default jsonResponse;
